{
	"id": "ELSA-2021-1631",
	"advisories": [
		{
			"content": {
				"id": "ELSA-2021-1631",
				"title": "ELSA-2021-1631:  python-urllib3 security update (MODERATE)",
				"description": "[1.24.2-5.0.1]\n- set RECENT_DATE to 01/30/2019 to make checks happy [Orabug: 30228991]\n\n[1.24.2-5]\n- Security fix for CVE-2020-26137\nResolves: rhbz#1883889",
				"severity": [
					{
						"type": "vendor",
						"source": "linux.oracle.com/security",
						"vendor": "MODERATE"
					}
				],
				"references": [
					{
						"source": "linux.oracle.com/security",
						"url": "https://linux.oracle.com/cve/CVE-2020-26137.html"
					},
					{
						"source": "linux.oracle.com/security",
						"url": "https://linux.oracle.com/errata/ELSA-2021-1631.html"
					}
				],
				"published": "2021-05-25T00:00:00Z"
			},
			"ecosystems": [
				"oracle:8"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-26137",
				"references": [
					{
						"source": "linux.oracle.com/security",
						"url": "https://linux.oracle.com/cve/CVE-2020-26137.html"
					}
				]
			},
			"ecosystems": [
				"oracle:8"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "oracle:8",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python3-urllib3",
							"architectures": [
								"aarch64",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:1.24.2-5.0.1.el8"
								}
							],
							"fixed": [
								"0:1.24.2-5.0.1.el8"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "oracle"
}
