{
	"id": "ELSA-2024-3275",
	"advisories": [
		{
			"id": "ELSA-2024-3275",
			"title": "ELSA-2024-3275:  python-dns security update (MODERATE)",
			"description": "[1.15.0-12]\n- Security fix for CVE-2023-29483\nResolves: RHEL-32630",
			"severity": [
				{
					"type": "vendor",
					"source": "linux.oracle.com/security",
					"vendor": "MODERATE"
				}
			],
			"references": [
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/cve/CVE-2023-29483.html"
				},
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/errata/ELSA-2024-3275.html"
				}
			],
			"published": "2024-05-29T00:00:00Z"
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2023-29483",
			"references": [
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/cve/CVE-2023-29483.html"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "oracle:8",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python3-dns",
							"architectures": [
								"aarch64",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:1.15.0-12.el8_10"
								}
							],
							"fixed": [
								"0:1.15.0-12.el8_10"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "oracle"
}
