{
	"id": "oval:com.oracle.elsa:def:20244260",
	"advisories": [
		{
			"id": "oval:com.oracle.elsa:def:20244260",
			"title": "\nELSA-2024-4260:  python-idna security update (MODERATE)\n",
			"description": "\n[2.5-7]\n- Fix patch application for security fix for CVE-2024-3651\nResolves: RHEL-32703\n\n[2.5-6]\n- Security fix for CVE-2024-3651\nResolves: RHEL-32703\n",
			"severity": [
				{
					"type": "vendor",
					"source": "linux.oracle.com/security",
					"vendor": "MODERATE"
				}
			],
			"references": [
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/cve/CVE-2024-3651.html"
				},
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/errata/ELSA-2024-4260.html"
				}
			],
			"published": "2024-07-03T00:00:00Z"
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2024-3651",
			"references": [
				{
					"source": "linux.oracle.com/security",
					"url": "https://linux.oracle.com/cve/CVE-2024-3651.html"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "oracle:8",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python3-idna",
							"architectures": [
								"aarch64",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:2.5-7.el8_10"
								}
							],
							"fixed": [
								"0:2.5-7.el8_10"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "oracle"
}
